# Generated by Django 4.1.4 on 2023-03-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_profile_profileimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AlterField(
            model_name='profile',
            name='id_user',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
