# Generated by Django 4.1.4 on 2023-03-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_follower_delete_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='user_following',
        ),
        migrations.AddField(
            model_name='follower',
            name='follower_user_id',
            field=models.ManyToManyField(blank=True, related_name='followers', to='core.profile'),
        ),
    ]
